all:
	gcc systemv_sem.c -o sysv_sem
	gcc systemv_sem_my.c -o sysv_sem_my -lpthread
	gcc posix_sem_named.c -o posix_sem_named -lpthread
	gcc posix_sem_unnamed.c -o posix_sem_unnamed -lpthread
	gcc posix_sem_unnamed_my.c -o posix_sem_unnamed_my -lpthread

